[project]
name = "au_para_2"
version = "0.0.2"
dependencies = [
]

[project.scripts]
au_para_2 = "au_para_2.entry:help"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"